### ISSUE TITLE
Slither Type not found MgvStructs.OfferPacked

### ISSUE THREAD

**Issue by 0xAurelou** [mangrovedao/mangrove-core#303]
Hello Mangrove Team,

I wanted to run ``slither`` a static analysis tools in order to check if there was not "classical" vulnerabilities in mangrove-core contracts.
However When I run the command to check if there is some vulnerabilities I have some issues. 

**To Reproduce**
1. Go to root of the repository (I assume that you did forge install before)
2. run ``slither . --filter-paths "lib|test" --exclude naming-convention --fail-medium``
3. See error

**Expected behavior**
Slither should run perfectly and tell you if you have high/medium/low severity issues in your contract

**Screenshots**
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/63618058/234932767-346ee2b9-a5b8-44f1-a09e-5e97491fe9aa.png">

**Desktop (please complete the following information):**
 - MacBook Pro m2
 - OS: MacOs 13.2.1

**Additional context**
No additional context needed

**Comment by adhusson** [comment]
Hi, unfortunately as of 4594917c0d35cfe49fbcc6f3f594d995c83129de it fails because slither does not work with qualified imports and has additional parsing bugs that prevent it from working with the Solidity features we use. I tried to get it to work a while ago; I just retried reading this issue and here is what happens:

- Qualified imports are not supported.
- Removing qualified imports and replacing all nested calls `MgvStructs.(...)` with the naked call still yields a bug related to user-defined types (it fails an `assert isinstance(t,..)` in the initialisation of a `UserDefinedType` because `t` somehow is `None`).
- For some reason, flattening removes this issue; but it is not easy to flatten. Unfortunately flatteners I tried do not deal with the name shadowing that happens when you remove one layer of nesting.
- You can reach a working file if, after flattening, you remove duplicate SPDX Licenses, rename all shadowed Libraries, variables and functions. Then you can run slither on the flattened Mangrove.sol

Unfortunately the result is one spurious "sends eth to arbitrary user" (user is arbitrary by definition), about 70 spurious reentrancy warnings because Mangrove's reentrancy protection is fine-grained, and a variety of other minor ones that are also spurious in my opinion (relying on local vars' uninitialized values: is part of the spec, using timestamp comparison: is OK, call to void constructor: is explicit thus safer, use of assembly: is necessary, unused code: actually used but elsewhere, pragma format: intentional, use of low-level calls: necessary, variable name too similar: one of them is not user-facing)

There is one correct warning about MgvGovernable's state variable `governance` being shadowed by its descendants' `AbstractMangrove` an `Mangrove`'s `governance` constructor argument, and another correct one about using snake_case instead of mixedCase).

This is similar to the result I got last time where I had to do the same refactoring to get slither to work. Unfortunately the poor quality of the detections combined with its inability to parse syntactically correct Solidity mean that I personally recommend against supporting it at all.

**Comment by 0xAurelou** [comment]
I think it's better to close this issue since the problem doesn't come from Mangrove and is more a general Slither AST problem that will probably won't be fix ☹️ 

Thanks for the help @adhusson @espendk 🙏
