### ISSUE TITLE
Simplify `marketOrder` flow

### ISSUE THREAD

**Issue by adhusson** [mangrovedao/mangrove-core#481]
Followup to #461.

Since moving to ticks, we have 72 bits available in `offer`. I think moving `gasreq` from `offerDetail` to `offer` make sense. It would reduce gas use in some situations, and mainly here it may remove one call to `endInternalMarketOrder` because we could just add `|| gasleft() < ...` to the big `if` at the beginning of `internalMarketOrder`. With the proviso that updating `mor.gasreqLeft` early is not a problem (@lnist wdyt?)

By removing one call to it we would then be able to inline it.

**Comment by lnist** [comment]
Yes it makes sense. I also really like the idea of being able to store some custom data in an offer when doing newoffer/updateoffer which the maker can then access - since we have available bits. For instance 32 bits for an offerId for Kandel. But it may remove the ability to put protocol-data there later.

**Comment by adhusson** [comment]
Do we have use cases in the strats? It is interesting in principle but I agree that once in, there's no out...

**Comment by lnist** [comment]
For Kandel, with offers storing prices I think we can go almost strat-storage-less (except we probably want to store "pending" amounts (amounts not currently offerable due to density requirements).
An offer can store its dual offer's offer id in this extra data - and since each offer knows its own price we don't have to store that either. 

Maybe we could do it as an "undocumented" feature (non-announced) with a remark saying it can be removed in future versions :D

**Comment by lnist** [comment]
It could also be used to store the Expiry of MangroveOrders

**Comment by adhusson** [comment]
This issue is pending #461 which may not end up being merged so #461 closes #481

**Comment by lnist** [comment]
Closed by https://github.com/mangrovedao/mangrove-core/pull/461
